name: CI - Lint and Test

on:
  push:
    branches: ["main"]
  pull_request:

jobs:
  lint-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
          cache-dependency-path: project/package.json

      - name: Install dependencies (project)
        working-directory: project
        run: npm install

      - name: Run lint
        working-directory: project
        run: npm run lint

      - name: Run tests
        working-directory: project
        run: npm test
